# AgentTree Configuration
# This file is the source of truth for all workflow configuration.
# See https://github.com/davefowler/agenttree for documentation.

default_tool: claude
default_model: opus
port_range: 9001-9099
project: "agenttree"
worktrees_dir: .worktrees

# Allow approving own PRs (skips PR approval check - for solo projects)
allow_self_approval: true

commands:
  test: uv run pytest
  lint: "uv run mypy agenttree || echo 'Lint warnings (optional)'"
  git_branch: git branch --show-current
  files_changed: "git diff --stat main...HEAD | grep -c '|' || echo 0"
  lines_added: "git diff --stat main...HEAD | tail -1 | awk '{print $4}' || echo 0"
  lines_removed: "git diff --stat main...HEAD | tail -1 | awk '{print $6}' || echo 0"
  duplicates: "uv run pylint --enable=duplicate-code agenttree/ 2>&1 | head -50"

tools:
  claude:
    command: claude
    skip_permissions: true
    startup_prompt: "Read TASK.md - it has your issue ID, stage, and workflow instructions. You MUST follow the staged workflow."
  aider:
    command: aider
    startup_prompt: /read TASK.md
  codex:
    command: codex
    startup_prompt: "Read TASK.md for your instructions."

# Role configurations
roles:
  manager:
    description: "Human-driven manager"
    process: "agenttree run"

  developer:
    description: "Default AI agent"
    container:
      image: agenttree-agent:latest
    tool: claude
    model: opus

  reviewer:
    description: "Independent code reviewer using Claude"
    container:
      image: agenttree-agent:latest
    tool: claude
    model: sonnet
    skill: independent_review.md

# Workflow flows
# The default flow defines stages inline (dict). Secondary flows reference
# stages by dot path (list). A bare stage name like "implement" expands to
# all its substages in definition order.
flows:
  default:
    stages:
      backlog:
        is_parking_lot: true

      explore:
        color: "#f97316"
        substages:
          define:
            output: problem.md
            pre_completion:
              - title_set:
              - section_check:
                  file: problem.md
                  section: Context
                  expect: not_empty
              - has_list_items:
                  file: problem.md
                  section: Possible Solutions

          research:
            output: research.md
            post_start:
              - create_file:
                  template: research.md
                  dest: research.md
            pre_completion:
              - section_check:
                  file: research.md
                  section: Relevant Files
                  expect: not_empty
              - section_check:
                  file: research.md
                  section: Existing Patterns
                  expect: not_empty

      plan:
        color: "#eab308"
        substages:
          draft:
            output: spec.md
            post_start:
              - create_file:
                  template: spec.md
                  dest: spec.md
            pre_completion:
              - section_check:
                  file: spec.md
                  section: Approach
                  expect: not_empty
              - has_list_items:
                  file: spec.md
                  section: Files to Modify
              - has_list_items:
                  file: spec.md
                  section: Implementation Steps
              - section_check:
                  file: spec.md
                  section: Test Plan
                  expect: not_empty

          assess:
            output: spec_review.md
            post_start:
              - create_file:
                  template: spec_review.md
                  dest: spec_review.md
            pre_completion:
              - section_check:
                  file: spec_review.md
                  section: Assessment Summary
                  expect: not_empty

          revise:
            output: spec.md

          review:
            human_review: true
            review_doc: spec.md
            pre_completion:
              - file_exists: spec.md
              - section_check:
                  file: spec.md
                  section: Approach
                  expect: not_empty
              - rebase:

      implement:
        color: "#22c55e"
        substages:
          setup: {}
          code: {}
          debug:
            skill: implement/debug.md
          code_review:
            output: review.md
            post_start:
              - create_file:
                  template: review.md
                  dest: review.md
            pre_completion:
              - run:
                  command: uv run pytest
                  must_pass: true
                  timeout: 900
              - run:
                  command: uv run mypy agenttree || echo "mypy warnings (pre-existing)"
                  must_pass: true
                  timeout: 300
              - section_check:
                  file: review.md
                  section: Self-Review Checklist
                  expect: all_checked
              - section_check:
                  file: review.md
                  section: Critical Issues
                  expect: empty
                  on_fail: address_review
          address_review:
            post_completion:
              - rollback:
                  to: code_review
                  max_rollbacks: 5
          wrapup:
            pre_completion:
              - wrapup_verified: review.md
          feedback:
            output: feedback.md
            pre_completion:
              - has_commits:
              - file_exists: review.md
              - section_check:
                  file: review.md
                  section: Critical Issues
                  expect: empty

          # Independent code review by a specialized review agent
          independent_review:
            role: reviewer
            output: independent_review.md
            skill: independent_review.md
            pre_completion:
              - file_exists: independent_review.md
              - section_check:
                  file: independent_review.md
                  section: Review Findings
                  expect: not_empty
              - checkbox_checked:
                  file: independent_review.md
                  checkbox: Approve
                  on_fail: address_independent

          # Implementing agent addresses review feedback
          address_independent:
            redirect_only: true
            role: developer
            output: independent_review_response.md
            skill: address_independent.md
            post_start:
              - create_file:
                  template: independent_review_response.md
                  dest: independent_review_response.md
            pre_completion:
              - section_check:
                  file: independent_review_response.md
                  section: Changes Made
                  expect: not_empty
            post_completion:
              - rollback:
                  to: independent_review
                  max_rollbacks: 5

          # UI review - only runs when needs_ui_review is true
          ui_review:
            condition: "{{ needs_ui_review }}"
            role: developer
            output: ui_review.md
            skill: ui_review.md
            post_start:
              - create_file:
                  template: ui_review.md
                  dest: ui_review.md
            pre_completion:
              - file_exists: ui_review.md
              - section_check:
                  file: ui_review.md
                  section: Screenshots Reviewed
                  expect: not_empty

          # CI wait and human review
          ci_wait:
            post_start:
              - create_pr:
            pre_completion:
              - ci_check:

          review:
            human_review: true
            role: manager
            review_doc: review.md
            pre_completion:
              - pr_approved:

      knowledge_base:
        color: "#8b5cf6"
        role: developer
        skill: knowledge_base.md

      accepted:
        is_parking_lot: true
        color: "#6b7280"
        role: manager
        post_start:
          - merge_pr:
          - cleanup_agent:
          - start_blocked_issues:

      not_doing:
        is_parking_lot: true
        redirect_only: true
        color: "#6b7280"

  # Quick flow for small issues that skip research and planning stages
  quick:
    stages:
      - backlog
      - explore.define
      - implement
      - accepted

  # Abandoned issues - only reachable via redirect
  not_doing:
    stages:
      - not_doing

default_flow: default

# Controller hooks for dogfooding
manager_hooks:
  post_sync:
    - cleanup_resources:
        log_file: _agenttree/logs/cleanup.log
