default_tool: claude
port_range: 9001-9099
project: agenttree
tools:
  aider:
    command: aider --model sonnet
    startup_prompt: /read TASK.md
  claude:
    command: claude
    startup_prompt: "First run: agenttree status --issue <ID> to check your stage. Read CLAUDE.md for workflow rules. Then check TASK.md."
worktrees_dir: .worktrees
