default_tool: claude
default_model: opus
port_range: 9001-9099
project: agenttree
tools:
  aider:
    command: aider --model sonnet
    startup_prompt: /read TASK.md
  claude:
    command: claude
    startup_prompt: "Read TASK.md - it has your issue ID, stage, and workflow instructions. You MUST follow the staged workflow."
worktrees_dir: .worktrees
