default_tool: claude
port_range: 8001-8009
project: agenttree
tools:
  aider:
    command: aider --model sonnet
    startup_prompt: /read TASK.md
  claude:
    command: claude
    startup_prompt: Check TASK.md and start working on it.
worktrees_dir: ~/Projects/worktrees
