# AgentTree Configuration
# This file is the source of truth for all workflow configuration.
# See https://github.com/davefowler/agenttree for documentation.

default_tool: claude
default_model: opus
port_range: 9001-9099
project: "agenttree"
worktrees_dir: .worktrees

commands:
  test: uv run pytest
  lint: "uv run mypy agenttree || echo 'Lint warnings (optional)'"
  # serve: "uv run uvicorn app:app --port $PORT"  # Dev server (port auto-assigned per issue)
  git_branch: git branch --show-current
  files_changed: "git diff --stat main...HEAD | grep -c '|' || echo 0"
  lines_added: "git diff --stat main...HEAD | tail -1 | awk '{print $4}' || echo 0"
  lines_removed: "git diff --stat main...HEAD | tail -1 | awk '{print $6}' || echo 0"

tools:
  claude:
    command: claude
    skip_permissions: true
    startup_prompt: "Read TASK.md - it has your issue ID, stage, and workflow instructions. You MUST follow the staged workflow."
  aider:
    command: aider
    startup_prompt: /read TASK.md
  codex:
    command: codex
    startup_prompt: "Read TASK.md for your instructions."

# Host configurations
# Hosts are execution environments that handle stages in the workflow.
# Each host can specify container settings, AI tool, model, and skills.
hosts:
  # Controller: Human-driven, runs on host machine (no container)
  # Runs the sync server which spawns agents and runs hooks
  controller:
    description: "Human-driven controller"
    process: "agenttree serve"  # Runs in tmux, handles syncs

  # Default AI agent: runs in container
  agent:
    description: "Default AI agent"
    container:
      image: agenttree-agent:latest
    tool: claude
    model: opus

  # Custom review agent host
  review:
    description: "Independent code reviewer using Claude"
    container:
      image: agenttree-agent:latest
    tool: claude
    model: sonnet
    skill: agents/review.md

stages:
  - name: backlog

  - name: define
    output: problem.md
    pre_completion:
      - title_set:  # Ensure issue has a real title, not "(untitled)"
      - section_check:
          file: problem.md
          section: Context
          expect: not_empty
      - has_list_items:
          file: problem.md
          section: Possible Solutions
    substages:
      refine: {}

  - name: research
    output: research.md
    post_start:
      - create_file:
          template: research.md
          dest: research.md
    pre_completion:
      - section_check:
          file: research.md
          section: Relevant Files
          expect: not_empty
      - section_check:
          file: research.md
          section: Existing Patterns
          expect: not_empty
    substages:
      explore: {}
      document: {}

  - name: plan
    output: spec.md
    post_start:
      - create_file:
          template: spec.md
          dest: spec.md
    pre_completion:
      - section_check:
          file: spec.md
          section: Approach
          expect: not_empty
      - has_list_items:
          file: spec.md
          section: Files to Modify
      - has_list_items:
          file: spec.md
          section: Implementation Steps
      - section_check:
          file: spec.md
          section: Test Plan
          expect: not_empty
    substages:
      draft: {}
      refine: {}

  - name: plan_assess
    output: spec_review.md
    post_start:
      - create_file:
          template: spec_review.md
          dest: spec_review.md
    pre_completion:
      - section_check:
          file: spec_review.md
          section: Assessment Summary
          expect: not_empty

  - name: plan_revise
    output: spec.md

  - name: plan_review
    human_review: true
    pre_completion:
      - file_exists: spec.md
      - section_check:
          file: spec.md
          section: Approach
          expect: not_empty
      - rebase:

  - name: implement
    substages:
      setup: {}
      code: {}
      code_review:
        output: review.md
        post_start:
          - create_file:
              template: review.md
              dest: review.md
        pre_completion:
          - run:
              command: uv run pytest tests/unit -q
              must_pass: true
          - run:
              command: uv run mypy agenttree || echo "mypy warnings (pre-existing errors in codebase - see issue for cleanup)"
              must_pass: true
          - section_check:
              file: review.md
              section: Self-Review Checklist
              expect: all_checked
      address_review: {}
      wrapup:
        pre_completion:
          - wrapup_verified: review.md
      feedback:
        output: feedback.md
        pre_completion:
          - has_commits:
          - file_exists: review.md
          - section_check:
              file: review.md
              section: Critical Issues
              expect: empty

  # Independent code review by a specialized review agent (not the implementing agent)
  - name: independent_code_review
    host: review  # Custom agent host - spawned by controller
    output: independent_review.md
    skill: agents/review.md  # Custom skill file for this stage
    pre_completion:
      - file_exists: independent_review.md
      - section_check:
          file: independent_review.md
          section: Review Findings
          expect: not_empty
      - checkbox_checked:
          file: independent_review.md
          checkbox: Approve
          on_fail_stage: address_independent_review

  # Stage where implementing agent addresses review feedback
  # Only reachable via StageRedirect when reviewer doesn't approve
  - name: address_independent_review
    redirect_only: true  # Not in normal progression, only via redirect
    host: agent  # Back to the implementing agent
    output: independent_review_response.md
    skill: address_independent_review.md
    post_start:
      - version_file:
          file: independent_review.md
      - version_file:
          file: independent_review_response.md
      - create_file:
          template: independent_review_response.md
          dest: independent_review_response.md
    pre_completion:
      - loop_check:
          count_files: independent_review_v*.md
          max: 5
          error: "Review loop exceeded 5 iterations. Escalating to human review."
      - section_check:
          file: independent_review_response.md
          section: Changes Made
          expect: not_empty
    post_completion:
      - rollback:
          to_stage: independent_code_review

  - name: implementation_review
    human_review: true
    host: controller  # Host handles PR creation (agents can't push)
    post_start:
      - create_pr:
    substages:
      ci_wait:
        pre_completion:
          - ci_check:
              timeout: 600
              poll_interval: 30
            host_only: true
      review: {}
    pre_completion:
      - pr_approved:

  - name: knowledge_base
    host: agent
    skill: knowledge_base.md

  - name: accepted
    terminal: true
    host: controller  # Host handles merge/cleanup (agents can't push)
    post_start:
      - merge_pr:
      - cleanup_agent:
      - start_blocked_issues:

  - name: not_doing
    terminal: true
